[general]
appName = "Connectors Test"
downloadsPath = "/home/<user>/downloads"

[database]
host   = "localhost"
port   = "5432"
database = "conns_test"
schemaCreationOrder = ["public", "system", "ecb", "maxmind"] # must be updated when schemas are added / removed. Also need to add to schemas.sql

[dbSuperUser]
userName = "postgres"
password = ""

[dbOwnerUser]
userName = "conns_owner" # this PG user owns all database objects
password = "123"

[maxmind]
accountId = ""
licenseKey = ""