
CREATE TABLE aws.api_call
(	
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attempt int_positive,
  created_at tracking_at,
  created_at_date date NOT NULL GENERATED ALWAYS AS (date(created_at AT TIME ZONE 'Europe/Berlin')) STORED, -- for easy filtering by date
  duration_ms bigint NOT NULL CHECK (duration_ms >= 0),
  endpoint text NOT NULL CHECK (endpoint != ''),
  page int_positive,
  result text NOT NULL
);
COMMENT ON TABLE aws.api_call IS 'shortname: aws_call';


CREATE TABLE aws.user_security_group_rule
(	
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at tracking_at,
  security_group_rule_id text_short_mandatory UNIQUE, -- natural key. Rule ID copied from AWS console
  user_shortname text_short_mandatory -- string that must also be written in the rule's description, e.g. 'bob' or 'alice-smith'
);
COMMENT ON TABLE aws.user_security_group_rule IS 'shortname: aws_usgr';
