
CREATE SCHEMA aws AUTHORIZATION <owner>;
COMMENT ON SCHEMA aws IS 'shortname: aws';

-- as needed
GRANT USAGE ON SCHEMA aws TO <user>;
ALTER DEFAULT PRIVILEGES IN SCHEMA aws GRANT SELECT, UPDATE, INSERT, DELETE ON TABLES TO <user>;
ALTER DEFAULT PRIVILEGES IN SCHEMA aws GRANT USAGE, SELECT ON SEQUENCES TO <user>;
