
/*
if needed:
CREATE DOMAIN tracking_at AS timestamp with time zone NOT NULL DEFAULT now();
*/

CREATE SCHEMA ecb AUTHORIZATION <owner_user>;

/*
as needed:
GRANT USAGE ON SCHEMA ecb TO <cli_user>;
ALTER DEFAULT PRIVILEGES IN SCHEMA ecb GRANT SELECT, UPDATE, INSERT, DELETE ON TABLES TO <cli_user>;
ALTER DEFAULT PRIVILEGES IN SCHEMA ecb GRANT USAGE, SELECT ON SEQUENCES TO <cli_user>;
*/

CREATE TYPE ecb.frequency AS ENUM ('D', 'M');


CREATE TABLE ecb.currency
(	
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entry_at tracking_at,
  last_modified_at tracking_at,
  code text NOT NULL UNIQUE, -- natural key
  name text NOT NULL
);
COMMENT ON TABLE ecb.currency IS 'shortname: curr';


CREATE TABLE ecb.exchange_rate
(	
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  frequency ecb.frequency NOT NULL,
  from_currency_fk bigint NOT NULL REFERENCES ecb.currency(id),
  to_currency_fk bigint NOT NULL REFERENCES ecb.currency(id),
  rate numeric(12,4) NOT NULL,
  day date NOT NULL,
  entry_at tracking_at,
  last_modified_at tracking_at,
  UNIQUE (frequency, day, from_currency_fk, to_currency_fk)
);
COMMENT ON TABLE ecb.exchange_rate IS 'shortname: xr';


CREATE OR REPLACE VIEW ecb.v_exchange_rate AS
  SELECT
    xr.day,
    xr.frequency,
    xr.from_currency_fk,
    from_curr.code AS from_currency,
    xr.entry_at,
    xr.last_modified_at,
    xr.id,
    xr.rate,
    xr.to_currency_fk,
    to_curr.code AS to_currency
  FROM ecb.exchange_rate xr
  JOIN ecb.currency from_curr ON xr.from_currency_fk = from_curr.id
  JOIN ecb.currency to_curr ON xr.to_currency_fk = to_curr.id;
