
/*
if needed:
CREATE DOMAIN tracking_at AS timestamp with time zone NOT NULL DEFAULT now();
*/

CREATE SCHEMA ecb AUTHORIZATION <owner_user>;

/*
as needed:
GRANT USAGE ON SCHEMA ecb TO <cli_user>;
ALTER DEFAULT PRIVILEGES IN SCHEMA ecb GRANT SELECT, UPDATE, INSERT, DELETE ON TABLES TO <cli_user>;
ALTER DEFAULT PRIVILEGES IN SCHEMA ecb GRANT USAGE, SELECT ON SEQUENCES TO <cli_user>;
*/

CREATE TYPE ecb.frequency AS ENUM ('D', 'M');


CREATE TABLE ecb.currency
(	
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(3) NOT NULL UNIQUE CHECK (length(code) BETWEEN 2 AND 3), -- natural key
  created_at tracking_at,
  name varchar(500) NOT NULL CHECK (name != ''),
  updated_at tracking_at
);
COMMENT ON TABLE ecb.currency IS 'shortname: curr';


CREATE TABLE ecb.exchange_rate
(	
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at tracking_at,
  day date NOT NULL,
  frequency ecb.frequency NOT NULL,
  from_currency_fk bigint NOT NULL REFERENCES ecb.currency(id),
  rate numeric(12,4) NOT NULL,
  to_currency_fk bigint NOT NULL REFERENCES ecb.currency(id),
  updated_at tracking_at,
  UNIQUE (frequency, day, from_currency_fk, to_currency_fk)
);
COMMENT ON TABLE ecb.exchange_rate IS 'shortname: xr';

CREATE INDEX exchange_rate_freq_day_idx ON ecb.exchange_rate USING btree(frequency, day);
CLUSTER ecb.exchange_rate USING exchange_rate_freq_day_idx;



CREATE OR REPLACE VIEW ecb.v_exchange_rate AS
  SELECT
    xr.created_at,
    xr.day,
    xr.frequency,
    xr.from_currency_fk,
    from_curr.code AS from_currency,
    xr.id,
    xr.rate,
    xr.to_currency_fk,
    to_curr.code AS to_currency,
    xr.updated_at
  FROM ecb.exchange_rate xr
  JOIN ecb.currency from_curr ON xr.from_currency_fk = from_curr.id
  JOIN ecb.currency to_curr ON xr.to_currency_fk = to_curr.id;
