
CREATE SCHEMA ecb AUTHORIZATION <owner>;

-- as needed
GRANT USAGE ON SCHEMA ecb TO <user>;
ALTER DEFAULT PRIVILEGES IN SCHEMA ecb GRANT SELECT, UPDATE, INSERT, DELETE ON TABLES TO <user>;
ALTER DEFAULT PRIVILEGES IN SCHEMA ecb GRANT USAGE, SELECT ON SEQUENCES TO <user>;
