

CREATE TABLE ecb.api_call
(	
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attempt int_positive,
  created_at tracking_at,
  created_at_date date NOT NULL GENERATED ALWAYS AS (date(created_at AT TIME ZONE 'Europe/Berlin')) STORED, -- for easy filtering by date, change timezone as needed
  duration_ms bigint NOT NULL CHECK (duration_ms >= 0),
  endpoint text NOT NULL CHECK (endpoint != ''),
  method text_short_mandatory,
  page int_positive,
  result text NOT NULL,
  status_code int_gte0
);
COMMENT ON TABLE ecb.api_call IS 'shortname: ecb_call';


CREATE TABLE ecb.currency
(	
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(3) NOT NULL UNIQUE CHECK (length(code) BETWEEN 2 AND 3), -- natural key
  created_at tracking_at,
  name varchar(500) NOT NULL CHECK (name != ''),
  updated_at tracking_at
);
COMMENT ON TABLE ecb.currency IS 'shortname: curr';


CREATE TABLE ecb.exchange_rate
(	
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at tracking_at,
  day date NOT NULL,
  frequency ecb.frequency NOT NULL,
  from_currency_fk bigint NOT NULL REFERENCES ecb.currency(id),
  rate numeric(12,4) NOT NULL,
  to_currency_fk bigint NOT NULL REFERENCES ecb.currency(id),
  updated_at tracking_at,
  UNIQUE (frequency, day, from_currency_fk, to_currency_fk)
);
COMMENT ON TABLE ecb.exchange_rate IS 'shortname: xr';

CREATE INDEX exchange_rate_freq_day_idx ON ecb.exchange_rate USING btree(frequency, day);
CLUSTER ecb.exchange_rate USING exchange_rate_freq_day_idx;
