
CREATE TABLE system.ext_data_sync
(	
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at tracking_at,
  last_sync_at timestamptz NOT NULL,
  sync_key text_short_mandatory UNIQUE -- natural key
);
COMMENT ON TABLE system.ext_data_sync IS 'shortname: sys_eds';
