
CREATE SCHEMA maxmind AUTHORIZATION <owner>;
COMMENT ON SCHEMA maxmind IS 'shortname: mm';

-- as needed
GRANT USAGE ON SCHEMA maxmind TO <user>;
ALTER DEFAULT PRIVILEGES IN SCHEMA maxmind GRANT SELECT, UPDATE, INSERT, DELETE ON TABLES TO <user>;
ALTER DEFAULT PRIVILEGES IN SCHEMA maxmind GRANT USAGE, SELECT ON SEQUENCES TO <user>;
