

CREATE TABLE tedb.api_call
(	
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attempt int_positive,
  created_at tracking_at,
  created_at_date date NOT NULL GENERATED ALWAYS AS (date(created_at AT TIME ZONE 'Europe/Berlin')) STORED, -- for easy filtering by date, change timezone as needed
  duration_ms bigint NOT NULL CHECK (duration_ms >= 0),
  endpoint text NOT NULL CHECK (endpoint != ''),
  method text_short_mandatory,
  page int_positive,
  result text NOT NULL,
  status_code int_gte0
);
COMMENT ON TABLE tedb.api_call IS 'shortname: tedb_call';


CREATE TABLE tedb.vat_rate
(	
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_description text NOT NULL,
  category_identifier text_short,
  cn_codes text[] NOT NULL, -- goods
  comment text NOT NULL,
  cpa_codes text[] NOT NULL, -- services
  created_at tracking_at,
  member_state varchar(2) NOT NULL CHECK (member_state != ''),
  rate_type text_short_mandatory,
  rate numeric(9,6) NOT NULL CHECK (rate >= 0),
  situation_on date NOT NULL,
  "type" text_short_mandatory,
  updated_at tracking_at
);
COMMENT ON TABLE tedb.vat_rate IS 'shortname: vr';

CREATE INDEX vat_rate_situation_on_idx ON tedb.vat_rate USING btree(situation_on);
CLUSTER tedb.vat_rate USING vat_rate_situation_on_idx;
