
CREATE SCHEMA tedb AUTHORIZATION <owner>;

-- as needed
GRANT USAGE ON SCHEMA tedb TO <user>;
ALTER DEFAULT PRIVILEGES IN SCHEMA tedb GRANT SELECT, UPDATE, INSERT, DELETE ON TABLES TO <user>;
ALTER DEFAULT PRIVILEGES IN SCHEMA tedb GRANT USAGE, SELECT ON SEQUENCES TO <user>;
